### ISSUE TITLE
Cannot call DoLockApp()

### ISSUE THREAD

**Issue by klmitchell2** [GeoSn0w/Myriam#2]
With cycript I am trying to call `ViewController['_DoLockApp']` but there is no output. Is the `_` indicating that this is a class method? Or how else should I approach this?

**Comment by GeoSn0w** [comment]
The app was designed to be dealt with through IDA, Hopper or Radare2, no idea what you're seeing via Cycript.

**Comment by klmitchell2** [comment]
Thanks for the clarification!
